### ISSUE TITLE
la photo de dewi n'est pas sur instagram

### ISSUE THREAD

**Issue by satblip** [openfab-lab/gamification-fablab#4]
## contexte
Nous somme face à une urgence capitale, @DewiBrunet n'est pas sur le trombinoscope instagram !

## objectif

Avoir Dewi sur instagram

## proposition

L'attraper, le mettre devant le logo et prendre un photo, ensuite il faut la publier au plus vite

## Resultats

On aura beaucoup plus de visites de femmes et de personnages politique venant voire mayor Dewi

### rewards

On se sentira mieux

**Comment by DewiBrunet** [comment]
![images](https://user-images.githubusercontent.com/25649502/44916371-db5d5900-ad35-11e8-8f2b-e99c6d6bbda9.png)

**Comment by nicolasdb** [comment]
C'est fait

**Comment by nicolasdb** [comment]
ho, j'ai oublié le #mayordewi

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/44921814-e4edbd80-ad43-11e8-81a0-2ab1591a8ac6.png)

https://www.instagram.com/explore/tags/mayordewey/

**Comment by nicolasdb** [comment]
this close this issue 👍
